authors:
  aesanfiel:
    name: Andrés Espinosa Sanfiel
    description: AI Engineer | Agentic AI Systems & RAG Pipelines
    avatar: https://avatars.githubusercontent.com/Sanfiel91
    url: https://www.linkedin.com/in/aesanfiel/
